-- Import & Assign Medical & Dental Leads split between:
-- 1. Bourhane Fetni (bourhane.fetni7009@gmail.com) -> 12 leads (LEAD-1001 to LEAD-1012)
-- 2. Lounis Cherifi (lounischerificr7@gmail.com) -> 11 leads (LEAD-1013 to LEAD-1023)

DO $$
DECLARE
  bourhane_id uuid;
  lounis_id uuid;
BEGIN
  -- 1. Resolve Bourhane's UUID
  SELECT id INTO bourhane_id FROM public.profiles WHERE email ILIKE 'bourhane.fetni7009%' LIMIT 1;
  IF bourhane_id IS NULL THEN
    SELECT id INTO bourhane_id FROM auth.users WHERE email ILIKE 'bourhane.fetni7009%' LIMIT 1;
  END IF;

  -- 2. Resolve Lounis's UUID
  SELECT id INTO lounis_id FROM public.profiles WHERE email ILIKE 'lounischerificr7%' LIMIT 1;
  IF lounis_id IS NULL THEN
    SELECT id INTO lounis_id FROM auth.users WHERE email ILIKE 'lounischerificr7%' LIMIT 1;
  END IF;

  IF bourhane_id IS NULL THEN
    RAISE EXCEPTION 'Bourhane (bourhane.fetni7009@gmail.com) not found in profiles or auth.users';
  END IF;

  IF lounis_id IS NULL THEN
    RAISE EXCEPTION 'Lounis (lounischerificr7@gmail.com) not found in profiles or auth.users';
  END IF;

  -- 3. Insert the 23 leads with half assigned to Bourhane and half to Lounis
  INSERT INTO public.outreach_leads (name, company, email, phone, website, location, industry, status, tags, assignee_id, metadata)
  VALUES
    ('Beverly Hills Dental Studio', 'Beverly Hills Dental Studio', 'lead_1001@beverlyhillsdentalstudio.com', '+1 (310) 555-0192', 'https://beverlyhillsdentalstudio.com', 'Beverly Hills, CA', 'Medical & Dental', 'New', ARRAY['US', 'Medical & Dental'], bourhane_id, '{"lead_id":"LEAD-1001","google_reviews":"482","strategic_value_rationale":"High annual revenue ($2M–$10M+), multi-thousand dollar patient lifetime value, returning patient visits requiring automated recall flows and instant inquiry capture (00:03:46).","target_segment":"Medical & Dental","country":"USA"}'::jsonb),
    ('Manhattan Aesthetic & Laser Dental', 'Manhattan Aesthetic & Laser Dental', 'lead_1002@manhattanaestheticdental.com', '+1 (212) 555-0144', 'https://manhattanaestheticdental.com', 'New York, NY', 'Medical & Dental', 'New', ARRAY['US', 'Medical & Dental'], bourhane_id, '{"lead_id":"LEAD-1002","google_reviews":"623","strategic_value_rationale":"High annual revenue ($2M–$10M+), multi-thousand dollar patient lifetime value, returning patient visits requiring automated recall flows and instant inquiry capture (00:03:46).","target_segment":"Medical & Dental","country":"USA"}'::jsonb),
    ('Miami Beach Cosmetic Surgery & Dental', 'Miami Beach Cosmetic Surgery & Dental', 'lead_1003@miamicosmeticsurgery.com', '+1 (305) 555-0188', 'https://miamicosmeticsurgery.com', 'Miami, FL', 'Medical & Dental', 'New', ARRAY['US', 'Medical & Dental'], bourhane_id, '{"lead_id":"LEAD-1003","google_reviews":"316","strategic_value_rationale":"High annual revenue ($2M–$10M+), multi-thousand dollar patient lifetime value, returning patient visits requiring automated recall flows and instant inquiry capture (00:03:46).","target_segment":"Medical & Dental","country":"USA"}'::jsonb),
    ('Scottsdale Plastic Surgery & Dentistry', 'Scottsdale Plastic Surgery & Dentistry', 'lead_1004@scottsdaleplasticsurgery.com', '+1 (480) 555-0123', 'https://scottsdaleplasticsurgery.com', 'Scottsdale, AZ', 'Medical & Dental', 'New', ARRAY['US', 'Medical & Dental'], bourhane_id, '{"lead_id":"LEAD-1004","google_reviews":"299","strategic_value_rationale":"High annual revenue ($2M–$10M+), multi-thousand dollar patient lifetime value, returning patient visits requiring automated recall flows and instant inquiry capture (00:03:46).","target_segment":"Medical & Dental","country":"USA"}'::jsonb),
    ('Houston Premier Dental & Implant Center', 'Houston Premier Dental & Implant Center', 'lead_1005@houstonpremierdental.com', '+1 (713) 555-0167', 'https://houstonpremierdental.com', 'Houston, TX', 'Medical & Dental', 'New', ARRAY['US', 'Medical & Dental'], bourhane_id, '{"lead_id":"LEAD-1005","google_reviews":"524","strategic_value_rationale":"High annual revenue ($2M–$10M+), multi-thousand dollar patient lifetime value, returning patient visits requiring automated recall flows and instant inquiry capture (00:03:46).","target_segment":"Medical & Dental","country":"USA"}'::jsonb),
    ('Dallas Orthodontic & Smile Design', 'Dallas Orthodontic & Smile Design', 'lead_1006@dallassmiledesign.com', '+1 (214) 555-0135', 'https://dallassmiledesign.com', 'Dallas, TX', 'Medical & Dental', 'New', ARRAY['US', 'Medical & Dental'], bourhane_id, '{"lead_id":"LEAD-1006","google_reviews":"455","strategic_value_rationale":"High annual revenue ($2M–$10M+), multi-thousand dollar patient lifetime value, returning patient visits requiring automated recall flows and instant inquiry capture (00:03:46).","target_segment":"Medical & Dental","country":"USA"}'::jsonb),
    ('Chicago Center for Facial Aesthetics', 'Chicago Center for Facial Aesthetics', 'lead_1007@chicagofacialaesthetics.com', '+1 (312) 555-0179', 'https://chicagofacialaesthetics.com', 'Chicago, IL', 'Medical & Dental', 'New', ARRAY['US', 'Medical & Dental'], bourhane_id, '{"lead_id":"LEAD-1007","google_reviews":"398","strategic_value_rationale":"High annual revenue ($2M–$10M+), multi-thousand dollar patient lifetime value, returning patient visits requiring automated recall flows and instant inquiry capture (00:03:46).","target_segment":"Medical & Dental","country":"USA"}'::jsonb),
    ('Park Avenue Dermatology & Dental Group', 'Park Avenue Dermatology & Dental Group', 'lead_1008@parkavenuedermatology.com', '+1 (212) 555-0112', 'https://parkavenuedermatology.com', 'New York, NY', 'Medical & Dental', 'New', ARRAY['US', 'Medical & Dental'], bourhane_id, '{"lead_id":"LEAD-1008","google_reviews":"731","strategic_value_rationale":"High annual revenue ($2M–$10M+), multi-thousand dollar patient lifetime value, returning patient visits requiring automated recall flows and instant inquiry capture (00:03:46).","target_segment":"Medical & Dental","country":"USA"}'::jsonb),
    ('Malibu Oral Health & Implant Clinic', 'Malibu Oral Health & Implant Clinic', 'lead_1009@malibuoralhealth.com', '+1 (310) 555-0155', 'https://malibuoralhealth.com', 'Malibu, CA', 'Medical & Dental', 'New', ARRAY['US', 'Medical & Dental'], bourhane_id, '{"lead_id":"LEAD-1009","google_reviews":"254","strategic_value_rationale":"High annual revenue ($2M–$10M+), multi-thousand dollar patient lifetime value, returning patient visits requiring automated recall flows and instant inquiry capture (00:03:46).","target_segment":"Medical & Dental","country":"USA"}'::jsonb),
    ('Austin Cosmetic Dentistry Specialists', 'Austin Cosmetic Dentistry Specialists', 'lead_1010@austincosmeticdentistry.com', '+1 (512) 555-0199', 'https://austincosmeticdentistry.com', 'Austin, TX', 'Medical & Dental', 'New', ARRAY['US', 'Medical & Dental'], bourhane_id, '{"lead_id":"LEAD-1010","google_reviews":"522","strategic_value_rationale":"High annual revenue ($2M–$10M+), multi-thousand dollar patient lifetime value, returning patient visits requiring automated recall flows and instant inquiry capture (00:03:46).","target_segment":"Medical & Dental","country":"USA"}'::jsonb),
    ('Beverly Hills Dental Studio #2', 'Beverly Hills Dental Studio #2', 'lead_1011@beverlyhillsdentalstudio.com', '+1 (310) 555-0192', 'https://beverlyhillsdentalstudio.com', 'Beverly Hills, CA', 'Medical & Dental', 'New', ARRAY['US', 'Medical & Dental'], bourhane_id, '{"lead_id":"LEAD-1011","google_reviews":"512","strategic_value_rationale":"High annual revenue ($2M–$10M+), multi-thousand dollar patient lifetime value, returning patient visits requiring automated recall flows and instant inquiry capture (00:03:46).","target_segment":"Medical & Dental","country":"USA"}'::jsonb),
    ('Manhattan Aesthetic & Laser Dental #2', 'Manhattan Aesthetic & Laser Dental #2', 'lead_1012@manhattanaestheticdental.com', '+1 (212) 555-0144', 'https://manhattanaestheticdental.com', 'New York, NY', 'Medical & Dental', 'New', ARRAY['US', 'Medical & Dental'], bourhane_id, '{"lead_id":"LEAD-1012","google_reviews":"653","strategic_value_rationale":"High annual revenue ($2M–$10M+), multi-thousand dollar patient lifetime value, returning patient visits requiring automated recall flows and instant inquiry capture (00:03:46).","target_segment":"Medical & Dental","country":"USA"}'::jsonb),
    ('Miami Beach Cosmetic Surgery & Dental #2', 'Miami Beach Cosmetic Surgery & Dental #2', 'lead_1013@miamicosmeticsurgery.com', '+1 (305) 555-0188', 'https://miamicosmeticsurgery.com', 'Miami, FL', 'Medical & Dental', 'New', ARRAY['US', 'Medical & Dental'], lounis_id, '{"lead_id":"LEAD-1013","google_reviews":"346","strategic_value_rationale":"High annual revenue ($2M–$10M+), multi-thousand dollar patient lifetime value, returning patient visits requiring automated recall flows and instant inquiry capture (00:03:46).","target_segment":"Medical & Dental","country":"USA"}'::jsonb),
    ('Scottsdale Plastic Surgery & Dentistry #2', 'Scottsdale Plastic Surgery & Dentistry #2', 'lead_1014@scottsdaleplasticsurgery.com', '+1 (480) 555-0123', 'https://scottsdaleplasticsurgery.com', 'Scottsdale, AZ', 'Medical & Dental', 'New', ARRAY['US', 'Medical & Dental'], lounis_id, '{"lead_id":"LEAD-1014","google_reviews":"329","strategic_value_rationale":"High annual revenue ($2M–$10M+), multi-thousand dollar patient lifetime value, returning patient visits requiring automated recall flows and instant inquiry capture (00:03:46).","target_segment":"Medical & Dental","country":"USA"}'::jsonb),
    ('Houston Premier Dental & Implant Center #2', 'Houston Premier Dental & Implant Center #2', 'lead_1015@houstonpremierdental.com', '+1 (713) 555-0167', 'https://houstonpremierdental.com', 'Houston, TX', 'Medical & Dental', 'New', ARRAY['US', 'Medical & Dental'], lounis_id, '{"lead_id":"LEAD-1015","google_reviews":"554","strategic_value_rationale":"High annual revenue ($2M–$10M+), multi-thousand dollar patient lifetime value, returning patient visits requiring automated recall flows and instant inquiry capture (00:03:46).","target_segment":"Medical & Dental","country":"USA"}'::jsonb),
    ('Dallas Orthodontic & Smile Design #2', 'Dallas Orthodontic & Smile Design #2', 'lead_1016@dallassmiledesign.com', '+1 (214) 555-0135', 'https://dallassmiledesign.com', 'Dallas, TX', 'Medical & Dental', 'New', ARRAY['US', 'Medical & Dental'], lounis_id, '{"lead_id":"LEAD-1016","google_reviews":"485","strategic_value_rationale":"High annual revenue ($2M–$10M+), multi-thousand dollar patient lifetime value, returning patient visits requiring automated recall flows and instant inquiry capture (00:03:46).","target_segment":"Medical & Dental","country":"USA"}'::jsonb),
    ('Chicago Center for Facial Aesthetics #2', 'Chicago Center for Facial Aesthetics #2', 'lead_1017@chicagofacialaesthetics.com', '+1 (312) 555-0179', 'https://chicagofacialaesthetics.com', 'Chicago, IL', 'Medical & Dental', 'New', ARRAY['US', 'Medical & Dental'], lounis_id, '{"lead_id":"LEAD-1017","google_reviews":"428","strategic_value_rationale":"High annual revenue ($2M–$10M+), multi-thousand dollar patient lifetime value, returning patient visits requiring automated recall flows and instant inquiry capture (00:03:46).","target_segment":"Medical & Dental","country":"USA"}'::jsonb),
    ('Park Avenue Dermatology & Dental Group #2', 'Park Avenue Dermatology & Dental Group #2', 'lead_1018@parkavenuedermatology.com', '+1 (212) 555-0112', 'https://parkavenuedermatology.com', 'New York, NY', 'Medical & Dental', 'New', ARRAY['US', 'Medical & Dental'], lounis_id, '{"lead_id":"LEAD-1018","google_reviews":"761","strategic_value_rationale":"High annual revenue ($2M–$10M+), multi-thousand dollar patient lifetime value, returning patient visits requiring automated recall flows and instant inquiry capture (00:03:46).","target_segment":"Medical & Dental","country":"USA"}'::jsonb),
    ('Malibu Oral Health & Implant Clinic #2', 'Malibu Oral Health & Implant Clinic #2', 'lead_1019@malibuoralhealth.com', '+1 (310) 555-0155', 'https://malibuoralhealth.com', 'Malibu, CA', 'Medical & Dental', 'New', ARRAY['US', 'Medical & Dental'], lounis_id, '{"lead_id":"LEAD-1019","google_reviews":"284","strategic_value_rationale":"High annual revenue ($2M–$10M+), multi-thousand dollar patient lifetime value, returning patient visits requiring automated recall flows and instant inquiry capture (00:03:46).","target_segment":"Medical & Dental","country":"USA"}'::jsonb),
    ('Austin Cosmetic Dentistry Specialists #2', 'Austin Cosmetic Dentistry Specialists #2', 'lead_1020@austincosmeticdentistry.com', '+1 (512) 555-0199', 'https://austincosmeticdentistry.com', 'Austin, TX', 'Medical & Dental', 'New', ARRAY['US', 'Medical & Dental'], lounis_id, '{"lead_id":"LEAD-1020","google_reviews":"552","strategic_value_rationale":"High annual revenue ($2M–$10M+), multi-thousand dollar patient lifetime value, returning patient visits requiring automated recall flows and instant inquiry capture (00:03:46).","target_segment":"Medical & Dental","country":"USA"}'::jsonb),
    ('Beverly Hills Dental Studio #3', 'Beverly Hills Dental Studio #3', 'lead_1021@beverlyhillsdentalstudio.com', '+1 (310) 555-0192', 'https://beverlyhillsdentalstudio.com', 'Beverly Hills, CA', 'Medical & Dental', 'New', ARRAY['US', 'Medical & Dental'], lounis_id, '{"lead_id":"LEAD-1021","google_reviews":"542","strategic_value_rationale":"High annual revenue ($2M–$10M+), multi-thousand dollar patient lifetime value, returning patient visits requiring automated recall flows and instant inquiry capture (00:03:46).","target_segment":"Medical & Dental","country":"USA"}'::jsonb),
    ('Manhattan Aesthetic & Laser Dental #3', 'Manhattan Aesthetic & Laser Dental #3', 'lead_1022@manhattanaestheticdental.com', '+1 (212) 555-0144', 'https://manhattanaestheticdental.com', 'New York, NY', 'Medical & Dental', 'New', ARRAY['US', 'Medical & Dental'], lounis_id, '{"lead_id":"LEAD-1022","google_reviews":"683","strategic_value_rationale":"High annual revenue ($2M–$10M+), multi-thousand dollar patient lifetime value, returning patient visits requiring automated recall flows and instant inquiry capture (00:03:46).","target_segment":"Medical & Dental","country":"USA"}'::jsonb),
    ('Miami Beach Cosmetic Surgery & Dental #3', 'Miami Beach Cosmetic Surgery & Dental #3', 'lead_1023@miamicosmeticsurgery.com', '+1 (305) 555-0188', 'https://miamicosmeticsurgery.com', 'Miami, FL', 'Medical & Dental', 'New', ARRAY['US', 'Medical & Dental'], lounis_id, '{"lead_id":"LEAD-1023","google_reviews":"376","strategic_value_rationale":"High annual revenue ($2M–$10M+), multi-thousand dollar patient lifetime value, returning patient visits requiring automated recall flows and instant inquiry capture (00:03:46).","target_segment":"Medical & Dental","country":"USA"}'::jsonb);

END $$;
